import t1 from "../src/assets/t1.png";
import t2 from "../src/assets/t2.jpg";
import t3 from "../src/assets/t3.jpg";
import t5 from "../src/assets/t5.jpg";
import t6 from "../src/assets/t6.png";
import t7 from "../src/assets/t7.jpg";
export const userData = [
  { month: "Jan", activeUsers: 900 },
  { month: "Feb", activeUsers: 1500 },
  { month: "Mar", activeUsers: 800 },
  { month: "Apr", activeUsers: 1600 },
  { month: "May", activeUsers: 2000 },
  { month: "Jun", activeUsers: 1700 },
  { month: "Jul", activeUsers: 2200 },
  { month: "Aug", activeUsers: 1700 },
  { month: "Sept", activeUsers: 1800 },
  { month: "Oct", activeUsers: 2000 },
  { month: "Nov", activeUsers: 2200 },
  { month: "Dec", activeUsers: 2500 },
];

export const OrderGrowthData = [
  { month: "Jan", vendors: 0 },
  { month: "Feb", vendors: 85 },
  { month: "Mar", vendors: 65 },
  { month: "Apr", vendors: 75 },
  { month: "May", vendors: 85 },
  { month: "Jun", vendors: 95 },
  { month: "Jul", vendors: 100 },
  { month: "Aug", vendors: 85 },
  { month: "Sep", vendors: 75 },
  { month: "Oct", vendors: 65 },
  { month: "Nov", vendors: 85 },
  { month: "Dec", vendors: 100 },
];

export const EarningGrowthData = [
  { month: "Jan", vendors: 0 },
  { month: "Feb", vendors: 85 },
  { month: "Mar", vendors: 65 },
  { month: "Apr", vendors: 75 },
  { month: "May", vendors: 85 },
  { month: "Jun", vendors: 95 },
  { month: "Jul", vendors: 100 },
  { month: "Aug", vendors: 85 },
  { month: "Sep", vendors: 75 },
  { month: "Oct", vendors: 65 },
  { month: "Nov", vendors: 85 },
  { month: "Dec", vendors: 100 },
];

export const AllOrderData = [
  {
    key: "#1201",
    no: "1",
    customer: "Shah Aman",
    products: "Root canal kit, Gloves",
    qty: "12",
    total: "123456",
    status: "Pending",
  },
  {
    key: "#1202",
    no: "2",
    customer: "Liam Smith",
    products: "Dental Mirror",
    qty: "5",
    total: "45678",
    status: "Processing",
  },
  {
    key: "#1203",
    no: "3",
    customer: "Emma Johnson",
    products: "Syringes",
    qty: "20",
    total: "98765",
    status: "Shipped",
  },
  {
    key: "#1204",
    no: "4",
    customer: "Noah Brown",
    products: "Gloves, Masks",
    qty: "50",
    total: "12300",
    status: "Cancelled",
  },
  {
    key: "#1205",
    no: "5",
    customer: "Olivia Jones",
    products: "X-ray Film",
    qty: "10",
    total: "23450",
    status: "Shipped",
  },
  {
    key: "#1206",
    no: "6",
    customer: "Ava Garcia",
    products: "Dental Drill",
    qty: "3",
    total: "76543",
    status: "Processing",
  },
  {
    key: "#1207",
    no: "7",
    customer: "William Martinez",
    products: "Face Shields",
    qty: "15",
    total: "11200",
    status: "Pending",
  },
  {
    key: "#1208",
    no: "8",
    customer: "James Rodriguez",
    products: "Anesthetic",
    qty: "8",
    total: "22000",
    status: "Cancelled",
  },
  {
    key: "#1209",
    no: "9",
    customer: "Sophia Lee",
    products: "Gloves",
    qty: "100",
    total: "15000",
    status: "Shipped",
  },
  {
    key: "#1210",
    no: "10",
    customer: "Benjamin Walker",
    products: "Masks",
    qty: "60",
    total: "9000",
    status: "Pending",
  },
  {
    key: "#1211",
    no: "11",
    customer: "Mia Hall",
    products: "Root canal kit",
    qty: "6",
    total: "54000",
    status: "Cancelled",
  },
  {
    key: "#1212",
    no: "12",
    customer: "Lucas Allen",
    products: "Gloves",
    qty: "20",
    total: "3000",
    status: "Processing",
  },
  {
    key: "#1213",
    no: "13",
    customer: "Charlotte Young",
    products: "Suction Tips",
    qty: "40",
    total: "6400",
    status: "Pending",
  },
  {
    key: "#1214",
    no: "14",
    customer: "Amelia Hernandez",
    products: "Sterilizer",
    qty: "1",
    total: "200000",
    status: "Shipped",
  },
  {
    key: "#1215",
    no: "15",
    customer: "Ethan King",
    products: "Cotton Rolls",
    qty: "70",
    total: "7000",
    status: "Processing",
  },
  {
    key: "#1216",
    no: "16",
    customer: "Harper Wright",
    products: "Syringes",
    qty: "30",
    total: "15000",
    status: "Pending",
  },
  {
    key: "#1217",
    no: "17",
    customer: "Daniel Lopez",
    products: "Face Shields",
    qty: "12",
    total: "1800",
    status: "Cancelled",
  },
  {
    key: "#1218",
    no: "18",
    customer: "Evelyn Hill",
    products: "Gloves",
    qty: "75",
    total: "11250",
    status: "Shipped",
  },
  {
    key: "#1219",
    no: "19",
    customer: "Matthew Scott",
    products: "Scalers",
    qty: "4",
    total: "3200",
    status: "Pending",
  },
  {
    key: "#1220",
    no: "20",
    customer: "Abigail Green",
    products: "Handpieces",
    qty: "2",
    total: "85000",
    status: "Processing",
  },
  {
    key: "#1221",
    no: "21",
    customer: "Henry Adams",
    products: "Gloves, Syringes",
    qty: "22",
    total: "4600",
    status: "Shipped",
  },
  {
    key: "#1222",
    no: "22",
    customer: "Emily Nelson",
    products: "Root canal kit",
    qty: "7",
    total: "63000",
    status: "Pending",
  },
  {
    key: "#1223",
    no: "23",
    customer: "Sebastian Carter",
    products: "Dental Mirror",
    qty: "9",
    total: "3400",
    status: "Cancelled",
  },
  {
    key: "#1224",
    no: "24",
    customer: "Elizabeth Mitchell",
    products: "Masks",
    qty: "90",
    total: "13500",
    status: "Shipped",
  },
  {
    key: "#1225",
    no: "25",
    customer: "Jack Perez",
    products: "Anesthetic",
    qty: "4",
    total: "8000",
    status: "Pending",
  },
  {
    key: "#1226",
    no: "26",
    customer: "Avery Roberts",
    products: "Gloves",
    qty: "120",
    total: "18000",
    status: "Processing",
  },
  {
    key: "#1227",
    no: "27",
    customer: "Logan Turner",
    products: "X-ray Film",
    qty: "6",
    total: "14000",
    status: "Shipped",
  },
  {
    key: "#1228",
    no: "28",
    customer: "Ella Phillips",
    products: "Scalers",
    qty: "10",
    total: "8000",
    status: "Pending",
  },
  {
    key: "#1229",
    no: "29",
    customer: "Harper Campbell",
    products: "Sterilizer",
    qty: "1",
    total: "195000",
    status: "Cancelled",
  },
  {
    key: "#1230",
    no: "30",
    customer: "Lucas Parker",
    products: "Dental Drill",
    qty: "2",
    total: "50000",
    status: "Shipped",
  },
];

export const products = [
  {
    id: 1,
    image: t1,
    name: "High-speed titanium handpiece",
    description:
      "High-speed titanium handpiece with quattro spray, ergonomic grip",
    price: 500.0,
    category: "Endodontics",
    brand: "Panora",
  },
  {
    id: 2,
    image: t2,
    name: "LED Curing Light – Cordless & Rechargeable",
    description: "LED Curing Light – Cordless & Rechargeable",
    price: 120.0,
    category: "Restorative",
    brand: "DentLight",
  },
  {
    id: 3,
    image: t3,
    name: "Digital Apex Locator",
    description: "Digital Apex Locator with Precision Sensors",
    price: 230.0,
    category: "Endodontics",
    brand: "ApexPro",
  },
  {
    id: 4,
    image: t1,
    name: "Ultrasonic Scaler – Multi-Tip Compatible",
    description: "Ultrasonic Scaler – Multi-Tip Compatible",
    price: 320.0,
    category: "Periodontics",
    brand: "SonicCare",
  },
  {
    id: 5,
    image: t5,
    name: "Portable X-ray Unit – Battery Operated",
    description: "Portable X-ray Unit – Battery Operated",
    price: 750.0,
    category: "Radiology",
    brand: "XPro",
  },
  {
    id: 6,
    image: t6,
    name: "Rubber Dam Kit – Complete with Clamps & Frame",
    description: "Rubber Dam Kit – Complete with Clamps & Frame",
    price: 80.0,
    category: "Endodontics",
    brand: "SealDent",
  },
  {
    id: 7,
    image: t7,
    name: "Intraoral Camera – HD with USB Connection",
    description: "Intraoral Camera – HD with USB Connection",
    price: 270.0,
    category: "Imaging",
    brand: "ViewDent",
  },
  {
    id: 8,
    image: t1,
    name: "Disposable Saliva Ejectors – Pack of 100",
    description: "Disposable Saliva Ejectors – Pack of 100",
    price: 15.0,
    category: "General",
    brand: "Ejecto",
  },
  {
    id: 9,
    image: t1,
    name: "Fiber Optic Dental Handpiece – Quiet & Lightweight",
    description: "Fiber Optic Dental Handpiece – Quiet & Lightweight",
    price: 460.0,
    category: "Prosthodontics",
    brand: "BrightLite",
  },
  {
    id: 10,
    image: t2,
    name: "Surgical Aspirator Tips – Autoclavable",
    description: "Surgical Aspirator Tips – Autoclavable",
    price: 25.0,
    category: "Surgery",
    brand: "AspiraMed",
  },
  {
    id: 11,
    image: t3,
    name: "Dental Tray Setup Kit – 5 Instruments Included",
    description: "Dental Tray Setup Kit – 5 Instruments Included",
    price: 55.0,
    category: "General",
    brand: "KitDent",
  },
  {
    id: 12,
    image: t1,
    name: "Implant Driver Set – Hex, Torx, Square",
    description: "Implant Driver Set – Hex, Torx, Square",
    price: 290.0,
    category: "Implantology",
    brand: "Implanta",
  },
  {
    id: 13,
    image: t5,
    name: "Cotton Roll Dispenser – Dustproof Lid",
    description: "Cotton Roll Dispenser – Dustproof Lid",
    price: 18.0,
    category: "Operatory",
    brand: "SafeRoll",
  },
  {
    id: 14,
    image: t6,
    name: "Air-Water Syringe Tips – Disposable, 250/box",
    description: "Air-Water Syringe Tips – Disposable, 250/box",
    price: 22.0,
    category: "Operatory",
    brand: "EZTips",
  },
  {
    id: 15,
    image: t7,
    name: "Dental Mirror – Front Surface, Anti-Fog",
    description: "Dental Mirror – Front Surface, Anti-Fog",
    price: 12.0,
    category: "Diagnostic",
    brand: "VisionPro",
  },
  {
    id: 16,
    image: t1,
    name: "Endo Motor with Cordless Handpiece",
    description: "Endo Motor with Cordless Handpiece",
    price: 610.0,
    category: "Endodontics",
    brand: "EndoMax",
    description: "Impression Tray Set – Upper & Lower",
  },
  {
    id: 17,
    image: t2,
    name: "Impression Tray Set – Upper & Lower",
    description: "Impression Tray Set – Upper & Lower",
    price: 40.0,
    category: "Prosthodontics",
    brand: "MoldDent",
  },
  {
    id: 18,
    image: t3,
    name: "Surgical Kit for Implant Placement – Complete System",
    description: "Surgical Kit for Implant Placement – Complete System",
    price: 990.0,
    category: "Surgery",
    brand: "ImplaKit",
  },
  {
    id: 19,
    image: t1,
    name: "Amalgam Carrier – Large Capacity",
    description: "Amalgam Carrier – Large Capacity",
    price: 38.0,
    category: "Restorative",
    brand: "CarryFill",
  },
  {
    id: 20,
    image: t5,
    name: "Dental Articulator – Semi-Adjustable",
    description: "Dental Articulator – Semi-Adjustable",
    price: 310.0,
    category: "Prosthodontics",
    brand: "Articulite",
  },
];
